### ISSUE TITLE
Translator pretrained models provides error while running the inference script.

### ISSUE THREAD

**Issue by PAAYAS** [warisqr007/ppg2ppg#3]
Dear author, it would be helpful, if you could update the pretrained models drive link as the translator model gives an error.

**Comment by warisqr007** [comment]
Hi @PAAYAS, I am no longer maintaining this repository. You can find an alternate implementation here: https://github.com/unilight/seq2seq-vc

**Comment by PAAYAS** [comment]
Thank you for your response.
